In [1]:
import numpy as np

In [2]:
array1 = np.arange(10) # 0...9
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### zeros
- shape은 아는데 값이 어떻게 될 지 모르는 경우에 사용 ( 값 초기화 용도 )

In [4]:
array2 = np.zeros((3, 2), dtype=np.int32) # axis1에 2칸, axis0에 3칸을 만들고 int32 타입 0으로 채움
array2

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [6]:
array3 = np.ones((3,2)) # axis1에 2칸, axis0에 3칸을 만들고 1로 채움
array3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
array4 = np.ones((3, 4, 10)) # axis2에 10칸, axis1에 4칸, axis0에 3칸을 만들고 1로 채움 / dtype 생략시 -> float64
array4

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

# reshape()
- reshape(2, 5): 2차원의 2X5 ndarray로 변환

In [15]:
re_array1 = array1.reshape(2, 5)
re_array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## reshape(-1, 5)
- -1에 해당하는 axis는 가변적으로
- -1에 해당하지 않는 axis (5)는 인자값으로 고정하여 ndarray의 shape를 변환

In [19]:
re_array2 = array1.reshape(-1, 2)
print(re_array2.shape)
re_array2

(5, 2)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## reshape()를 활용한 차원변환

In [23]:
array_1d = np.array([0, 1, 2, 3, 4])
print(array_1d.shape)
array_1d.reshape(-1, 1) # 2차원으로 변환하되 컬럼 axis 크기가 1로 고정

(5,)


array([[0],
       [1],
       [2],
       [3],
       [4]])

In [22]:
array_2d = np.array([
    [0],
    [1],
    [2],
    [3],
    [4]
])
print(array_2d.shape)
array_2d.reshape(-1,) # 1차원으로 변환

(5, 1)


array([0, 1, 2, 3, 4])