In [1]:
import numpy as np

# 단일 값 추출 - 1차원
- 위치 인덱스

In [9]:
array1 = np.arange(1, 11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
array1[0]

np.int64(1)

# 단일 값 추출 - 1차원
- 위치 인덱스

In [13]:
import pandas as pd

array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array_2d_df = pd.DataFrame(array_2d)
array_2d_df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [14]:
array_2d[0, 1]

np.int64(2)

# 슬라이싱(Slicing) - 1차원

In [15]:
array1 = np.arange(1, 11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
array1[:3]

array([1, 2, 3])

In [17]:
array1[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [18]:
array1[0:6]

array([1, 2, 3, 4, 5, 6])

In [19]:
array1[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 슬라이싱(Slicing) - 2차원

In [20]:
import pandas as pd

array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array_2d_df = pd.DataFrame(array_2d)
array_2d_df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [23]:
result = array_2d[0:2, 0:2]

show = pd.DataFrame(result)
show

0  1
0  1  2
1  4  5

In [24]:
result = array_2d[:, :]

show = pd.DataFrame(result)
show

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [25]:
result = array_2d[:2, 1:]

show = pd.DataFrame(result)
show

0  1
0  2  3
1  5  6

In [26]:
result = array_2d[:2, 0]

show = pd.DataFrame(result)
show

0
0  1
1  4