In [1]:
import numpy as np

In [2]:
list1 = [1, 2, 3]
print('list1 type:', type(list1))

array1 = np.array(list1)
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([
    [1,2,3],
    [2,3,4]
])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([
    [1,2,3]
])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

list1 type: <class 'list'>
array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


# 원소들의 데이터 타입

In [4]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


## 혼합 타입은 안됨
- 변수에 값은 들어가지만 문자열로 자동 형변환 됨
- 타입이 큰 쪽으로 형변환 됨

In [8]:
list2 = [1, 2.0, 'abc']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 3, 5.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2.0' 'abc'] <U32
[1. 3. 5.] float64


## 형변환
- .astype()

In [11]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
# array_float = array_int.astype(np.float64)
print(array_float, array_float.dtype)

array_int1= array_float.astype('int64')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int64
[1 2 3] int32
